/**
 * Public Admin-facing error codes for the request fulfilment API.
 * These are the ONLY codes the client should ever see — raw database
 * exception strings (request_admin_forbidden, ...) are mapped in
 * lib/admin/requests/fulfilment-errors.ts and never exposed.
 */
export const FULFILMENT_API_ERROR_CODES = {
  REQUEST_UNAUTHORIZED: "REQUEST_UNAUTHORIZED",
  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  REQUEST_STATUS_CONFLICT: "REQUEST_STATUS_CONFLICT",
  REQUEST_STATUS_UNCHANGED: "REQUEST_STATUS_UNCHANGED",
  REQUEST_TRANSITION_INVALID: "REQUEST_TRANSITION_INVALID",
  REQUEST_INVALID_STATUS: "REQUEST_INVALID_STATUS",
  REQUEST_FINAL_MEDIA_REQUIRED: "REQUEST_FINAL_MEDIA_REQUIRED",
  REQUEST_REJECTION_REASON_REQUIRED: "REQUEST_REJECTION_REASON_REQUIRED",
  REQUEST_NOTE_TOO_LONG: "REQUEST_NOTE_TOO_LONG",
  REQUEST_UPLOAD_NOT_ALLOWED: "REQUEST_UPLOAD_NOT_ALLOWED",
  REQUEST_FILE_INVALID: "REQUEST_FILE_INVALID",
  REQUEST_ASSET_NOT_FOUND: "REQUEST_ASSET_NOT_FOUND",
  REQUEST_ASSET_NOT_FINAL: "REQUEST_ASSET_NOT_FINAL",
  REQUEST_ASSET_NOT_UPLOADED: "REQUEST_ASSET_NOT_UPLOADED",
  REQUEST_ASSET_ALREADY_SUPERSEDED: "REQUEST_ASSET_ALREADY_SUPERSEDED",
  REQUEST_INVALID_BODY: "REQUEST_INVALID_BODY",
  REQUEST_UNKNOWN_ERROR: "REQUEST_UNKNOWN_ERROR",
} as const;

export type FulfilmentApiErrorCode =
  (typeof FULFILMENT_API_ERROR_CODES)[keyof typeof FULFILMENT_API_ERROR_CODES];
